// @ts-nocheck -- skip type checking
import * as blogPosts_9 from "../content/blog/web-performance-core-vitals.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_8 from "../content/blog/web-components-guide.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_7 from "../content/blog/typescript-5-5-features.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_6 from "../content/blog/react-server-components.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_5 from "../content/blog/react-18-concurrent-features.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_4 from "../content/blog/nextjs-scalable-architecture.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_3 from "../content/blog/nextjs-15-features.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_2 from "../content/blog/modern-css-2025.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_1 from "../content/blog/javascript-es2023-features.mdx?collection=blogPosts&hash=1754804524000"
import * as blogPosts_0 from "../content/blog/advanced-react-hooks.mdx?collection=blogPosts&hash=1754804524000"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blogPosts = _runtime.doc<typeof _source.blogPosts>([{ info: {"path":"advanced-react-hooks.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/advanced-react-hooks.mdx"}, data: blogPosts_0 }, { info: {"path":"javascript-es2023-features.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/javascript-es2023-features.mdx"}, data: blogPosts_1 }, { info: {"path":"modern-css-2025.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/modern-css-2025.mdx"}, data: blogPosts_2 }, { info: {"path":"nextjs-15-features.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/nextjs-15-features.mdx"}, data: blogPosts_3 }, { info: {"path":"nextjs-scalable-architecture.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/nextjs-scalable-architecture.mdx"}, data: blogPosts_4 }, { info: {"path":"react-18-concurrent-features.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/react-18-concurrent-features.mdx"}, data: blogPosts_5 }, { info: {"path":"react-server-components.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/react-server-components.mdx"}, data: blogPosts_6 }, { info: {"path":"typescript-5-5-features.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/typescript-5-5-features.mdx"}, data: blogPosts_7 }, { info: {"path":"web-components-guide.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/web-components-guide.mdx"}, data: blogPosts_8 }, { info: {"path":"web-performance-core-vitals.mdx","absolutePath":"D:/Web Dev/porto-2025/orbit/content/blog/web-performance-core-vitals.mdx"}, data: blogPosts_9 }]);